name: "Behavior-UI"

description: "Behavior filters and UI Patterns for the Behavior framework."

license: "MIT License"

version: "0.1"

sources:
 - Source/Accordion/Behavior.Fx.Accordion.js
 - Source/Autocompleter/Autocompleter.js
 - Source/Autocompleter/Autocompleter.JSONP.js
 - Source/Autocompleter/Autocompleter.Local.js
 - Source/Autocompleter/Autocompleter.Observer.js
 - Source/Autocompleter/Autocompleter.Remote.js
 - Source/Autocompleter/Behavior.Autocompleter.js
 - Source/Behavior.config.js
 - Source/Behavior.init.js
 - Source/Bootstrap/Bootstrap.js
 - Source/Bootstrap.Affix/Behavior.BS.Affix.js
 - Source/Bootstrap.Affix/Bootstrap.Affix.js
 - Source/Bootstrap.Carousel/Behavior.BS.Carousel.js
 - Source/Bootstrap.Carousel/Behavior.Slides.js
 - Source/Bootstrap.Carousel/Delegator.SetSlide.js
 - Source/Bootstrap.Carousel/Slides.js
 - Source/Bootstrap.Dropdown/Behavior.BS.Dropdown.js
 - Source/Bootstrap.Dropdown/Bootstrap.Dropdown.js
 - Source/Bootstrap.Form.Validator/Behavior.BS.FormValidator.js
 - Source/Bootstrap.Form.Validator/Behavior.FormValidator.BS.Tips.js
 - Source/Bootstrap.Form.Validator/Behavior.OnFormValidate.js
 - Source/Bootstrap.Form.Validator/Bootstrap.Form.Validator.Tips.js
 - Source/Bootstrap.MobileMenu/Behavior.MobileMenu.js
 - Source/Bootstrap.MobileMenu/MobileMenu.js
 - Source/Bootstrap.Popover/Behavior.BS.Popover.js
 - Source/Bootstrap.Popover/Bootstrap.Popover.js
 - Source/Bootstrap.Popup/Behavior.BS.Popup.FormRequest.js
 - Source/Bootstrap.Popup/Behavior.BS.Popup.js
 - Source/Bootstrap.Popup/Bootstrap.Popup.js
 - Source/Bootstrap.Popup/Delegator.BS.ShowPopup.js
 - Source/Bootstrap.Tabs/Behavior.BS.Tabs.js
 - Source/Bootstrap.Tooltip/Behavior.BS.Tooltip.js
 - Source/Bootstrap.Tooltip/Bootstrap.Tooltip.js
 - Source/Charts/Behavior.Chart.js
 - Source/Charts/Behavior.Chart.Pie.js
 - Source/Charts/Behavior.Chart.RangeMonitor.js
 - Source/Charts/Behavior.Chart.ShowPopup.js
 - Source/Charts/Behavior.Chart.Stock.js
 - Source/Charts/Behavior.ToSource.js
 - Source/Charts/Chart.js
 - Source/Charts/Chart.Pie.js
 - Source/Charts/Chart.Stock.js
 - Source/ColorPicker/Behavior.ColorPicker.js
 - Source/ColorPicker/ColorPicker.js
 - Source/ContinueScroll/Behavior.ContinueScroll.js
 - Source/ContinueScroll/ContinueScroll.js
 - Source/DatePicker/Behavior.DatePicker.js
 - Source/DatePicker/Locale.cs-CZ.DatePicker.js
 - Source/DatePicker/Locale.de-DE.DatePicker.js
 - Source/DatePicker/Locale.en-US.DatePicker.js
 - Source/DatePicker/Locale.es-ES-DatePicker.js
 - Source/DatePicker/Locale.fr-FR.DatePicker.js
 - Source/DatePicker/Locale.he-IL.DatePicker.js
 - Source/DatePicker/Locale.it-IT.DatePicker.js
 - Source/DatePicker/Locale.nl-NL.DatePicker.js
 - Source/DatePicker/Locale.pl-PL.DatePicker.js
 - Source/DatePicker/Locale.pt-BR.DatePicker.js
 - Source/DatePicker/Locale.ru-RU.DatePicker.js
 - Source/DatePicker/Picker.Attach.js
 - Source/DatePicker/Picker.Date.js
 - Source/DatePicker/Picker.Date.Range.js
 - Source/DatePicker/Picker.js
 - Source/Delegators/Delegator.AddRemoveClass.js
 - Source/Delegators/Delegator.Ajax.js
 - Source/Delegators/Delegator.CharsRemaining.js
 - Source/Delegators/Delegator.CheckAllOrNone.js
 - Source/Delegators/Delegator.Confirm.js
 - Source/Delegators/Delegator.EnableForm.js
 - Source/Delegators/Delegator.Fx.Reveal.js
 - Source/Delegators/Delegator.InputMirror.js
 - Source/Delegators/Delegator.Invoke.js
 - Source/Delegators/Delegator.Invoke.Toggle.js
 - Source/Delegators/Delegator.ScrollToElement.js
 - Source/Delegators/Delegator.SelectToSet.js
 - Source/Delegators/Delegator.SelectWithOther.js
 - Source/Delegators/Delegator.SetProperty.js
 - Source/Delegators/Delegator.ShowOnSelect.js
 - Source/Delegators/Delegator.SpinAndConfirm.js
 - Source/Delegators/Delegator.SpinOnClick.js
 - Source/Delegators/Delegator.SpinOnSubmit.js
 - Source/Delegators/Delegator.SubmitLink.js
 - Source/Delegators/Delegator.SubmitOnChange.js
 - Source/FlatUI/FlatUI.js
 - Source/FlatUI.FormValidator/Behavior.FlatUI.FormValidator.js
 - Source/FlatUI.FormValidator/FlatUI.FormValidator.js
 - Source/FlatUI.Select/Behavior.FlatUI.Select.js
 - Source/FlatUI.Select/FlatUI.Select.js
 - Source/Forms/Behavior.Filter.js
 - Source/Forms/Behavior.FormRequest.js
 - Source/Forms/Behavior.FormValidator.js
 - Source/Forms/Behavior.OverText.js
 - Source/Forms/Form.Filler.js
 - Source/Forms/Form.Filter.js
 - Source/FrameFlow/Behavior.FrameFlow.js
 - Source/FrameFlow/Delegator.FrameFlowControl.js
 - Source/FrameFlow/FrameFlow.js
 - Source/Fx.Progress/Fx.Progress.js
 - Source/GoogleMap/GoogleMap.js
 - Source/HtmlTable/Behavior.HtmlTable.js
 - Source/InteractiveList/Behavior.InteractiveList.js
 - Source/InteractiveList/Behavior.InteractiveMessageList.js
 - Source/InteractiveList/InteractiveList.js
 - Source/Mask/Mask.BoxModel.js
 - Source/Misc-Behaviors/Behavior.ClickOutToHide.js
 - Source/Misc-Behaviors/Behavior.Highlight.js
 - Source/Misc-Behaviors/Behavior.Invoke.js
 - Source/Misc-Behaviors/Behavior.SetMinSize.js
 - Source/Request/Behavior.PollForUpdate.js
 - Source/Request/Behavior.Request.BindData.js
 - Source/Request/Request.BindData.js
 - Source/Request/Request.Limit.js
 - Source/Request/Request.PollForUpdate.js
 - Source/ScrollTween/ScrollTween.js
 - Source/Slider.Modify/Behavior.Slider.Modify.js
 - Source/Slider.Modify/Slider.Modify.js
 - Source/Spinner/Spinner.CSS.js
 - Source/Swipe/Swipe.js
 - Source/Tabs/Behavior.Tabs.js
 - Source/Tabs/Behavior.Tabs.ShowAll.js
 - Source/Tabs/Tabs.Hash.js
 - Source/Tabs/Tabs.js
 - Source/Types/Event.HashChange.js
 - Source/Types/Number.js
 - Source/Utilities/CSSEvents.js
 - Source/Utilities/dbug.js
 - Source/Validators/Form.Validator.EasyUrl.js
 - Source/Validators/Form.Validator.NoSpaces.js
 - Source/Validators/Form.Validator.Range.js
 - Source/Validators/Form.Validator.Tag.js
